version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-apache
    ports:
      - "80:80"
    networks:
      - isolated



networks:
  isolated:
    driver: bridge